// Code generated by goctl-sdk. DO NOT EDIT.


export interface AddContactTagsRequest {
  tags: string[];
}


export interface ContactRequest {
  email: string;
  name?: string;
  phone?: string;
  company?: string;
  message?: string;
  source?: string;
  tags?: string[];
  list_slug?: string;
  utm_source?: string;
  utm_medium?: string;
  utm_campaign?: string;
  meta?: Record<string, string>;
}


export interface ContactResponse {
  id: string;
  email: string;
  name: string;
}


export interface EmailStatusResponse {
  message_id: string;
  to: string;
  subject: string;
  status: string;
  sent_at?: string;
  delivered_at?: string;
  opened_at?: string;
  clicked_at?: string;
  bounced_at?: string;
  bounce_type?: string;
  opens: number;
  clicks: number;
}


export interface EnrollSequenceRequest {
  sequence_slug: string;
  email: string;
  variables?: Record<string, string>;
  start_at_step?: number;
  scheduled_for?: string;
}


export interface EnrollSequenceResponse {
  success: boolean;
  enrollment_id: string;
  status: string;
  message?: string;
}


export interface ContactStatsPoint {
  date: string;
  new_contacts: number;
  unsubscribed: number;
  bounced: number;
  net_growth: number;
}


export interface GetContactStatsResponse {
  stats: ContactStatsPoint[];
  total_active: number;
  total_unsubscribed: number;
  total_bounced: number;
  net_growth: number;
}


export interface EmailStatsPoint {
  date: string;
  sent: number;
  delivered: number;
  opened: number;
  clicked: number;
  bounced: number;
  open_rate: number;
  click_rate: number;
}


export interface GetEmailStatsResponse {
  stats: EmailStatsPoint[];
  total_sent: number;
  total_delivered: number;
  total_opened: number;
  total_clicked: number;
  total_bounced: number;
  avg_open_rate: number;
  avg_click_rate: number;
}


export interface GlobalUnsubscribeRequest {
  email: string;
  reason?: string;
}


export interface ContactActivityInfo {
  event: string;
  timestamp: string;
  details?: string;
}


export interface ListContactActivityResponse {
  activities: ContactActivityInfo[];
}


export interface EmailEventInfo {
  event: string;
  timestamp: string;
  data?: string;
}


export interface ListEmailEventsResponse {
  events: EmailEventInfo[];
}


export interface SequenceEnrollmentInfo {
  enrollment_id: string;
  sequence_slug: string;
  sequence_name: string;
  status: string;
  current_step: number;
  total_steps: number;
  enrolled_at: string;
  next_email_at?: string;
  completed_at?: string;
  emails_sent: number;
  emails_opened: number;
  emails_clicked: number;
}


export interface ListSequenceEnrollmentsResponse {
  enrollments: SequenceEnrollmentInfo[];
}


export interface WebhookLogInfo {
  id: string;
  event: string;
  payload: string;
  status_code: number;
  response?: string;
  error?: string;
  duration_ms: number;
  delivered_at: string;
}


export interface ListWebhookLogsResponse {
  logs: WebhookLogInfo[];
}


export interface WebhookInfo {
  id: string;
  url: string;
  events: string[];
  active: boolean;
  created_at: string;
  deliveries_total: number;
  deliveries_success: number;
  deliveries_failed: number;
  last_delivery_at?: string;
  last_status?: number;
}


export interface ListWebhooksResponse {
  webhooks: WebhookInfo[];
}


export interface PauseSequenceRequest {
  email: string;
  sequence_slug: string;
}


export interface RegisterWebhookRequest {
  url: string;
  events: string[];
  secret?: string;
  active?: boolean;
}


export interface RegisterWebhookResponse {
  success: boolean;
  webhook_id: string;
  secret: string;
  message?: string;
}


export interface RemoveContactTagsRequest {
  tags: string[];
}


export interface Response {
  success: boolean;
  message?: string;
}


export interface ResumeSequenceRequest {
  email: string;
  sequence_slug: string;
}


export interface SDKContactInfo {
  id: string;
  email: string;
  name: string;
  phone?: string;
  company?: string;
  status: string;
  email_verified: boolean;
  tags: string[];
  lists: string[];
  custom_fields?: Record<string, string>;
  source?: string;
  emails_sent: number;
  emails_opened: number;
  emails_clicked: number;
  last_email_at?: string;
  last_open_at?: string;
  last_click_at?: string;
  created_at: string;
  updated_at: string;
}


export interface SendEmailRequest {
  to: string;
  template_slug?: string;
  subject?: string;
  body?: string;
  text_body?: string;
  from_name?: string;
  from_email?: string;
  reply_to?: string;
  variables?: Record<string, string>;
  tags?: string[];
  meta?: Record<string, string>;
}


export interface SendEmailResponse {
  success: boolean;
  message_id: string;
  status: string;
  message?: string;
}


export interface StatsOverviewResponse {
  total_contacts: number;
  new_contacts: number;
  active_contacts: number;
  emails_sent: number;
  emails_delivered: number;
  emails_opened: number;
  emails_clicked: number;
  emails_bounced: number;
  open_rate: number;
  click_rate: number;
  bounce_rate: number;
}


export interface SubscribeRequest {
  email: string;
  name?: string;
}


export interface TestWebhookResponse {
  success: boolean;
  status_code: number;
  response?: string;
  error?: string;
}


export interface TrackClickRequest {
  token: string;
  url: string;
}


export interface TrackConfirmRequest {
  token: string;
}


export interface TrackConfirmResponse {
  success: boolean;
  message?: string;
  redirect_url?: string;
}


export interface TrackOpenRequest {
  token: string;
}


export interface TrackUnsubscribeRequest {
  token: string;
}


export interface UnenrollSequenceRequest {
  email: string;
  sequence_slug?: string;
}


export interface UpdateContactRequest {
  name?: string;
  phone?: string;
  company?: string;
  custom_fields?: Record<string, string>;
}


export interface UpdateWebhookRequest {
  url?: string;
  events?: string[];
  active?: boolean;
}

